// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0UzoI731LFyStlvRZv40lJyWgtZ14TJw',
    appId: '1:594632936898:web:ce63524659fcbad339da5b',
    messagingSenderId: '594632936898',
    projectId: 'yanaseeb-2d773',
    authDomain: 'yanaseeb-2d773.firebaseapp.com',
    storageBucket: 'yanaseeb-2d773.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjHRjl2PVDAS6RilbkBJqVpx5aQdKrIx4',
    appId: '1:594632936898:android:7e36930c314e2ca039da5b',
    messagingSenderId: '594632936898',
    projectId: 'yanaseeb-2d773',
    storageBucket: 'yanaseeb-2d773.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxLVmG2fRSOAEBFqqy0QcQ1KIDgJJppR4',
    appId: '1:594632936898:ios:01c512464cd5dfc139da5b',
    messagingSenderId: '594632936898',
    projectId: 'yanaseeb-2d773',
    storageBucket: 'yanaseeb-2d773.appspot.com',
    iosClientId: '594632936898-osro46u8gar2sf7d35dam8biaes2k522.apps.googleusercontent.com',
    iosBundleId: 'com.example.yaNaseeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxLVmG2fRSOAEBFqqy0QcQ1KIDgJJppR4',
    appId: '1:594632936898:ios:01c512464cd5dfc139da5b',
    messagingSenderId: '594632936898',
    projectId: 'yanaseeb-2d773',
    storageBucket: 'yanaseeb-2d773.appspot.com',
    iosClientId: '594632936898-osro46u8gar2sf7d35dam8biaes2k522.apps.googleusercontent.com',
    iosBundleId: 'com.example.yaNaseeb',
  );
}
